# Stage 1: Build the Go binary
FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copy go.mod and go.sum and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Move to the cmd directory where main.go is located
WORKDIR /app/cmd

# Build the Go binary
RUN go build -o /app/main .

# Stage 2: Run the application in a lightweight container
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the pre-built binary and .env file from the builder stage
COPY --from=builder /app/main .
# COPY --from=builder /app/.env .

# Expose the necessary port (change this if you're using a different port in your app)
EXPOSE 8080

# Run the binary
CMD ["./main"]
