# PUT THIS FILE IN A SPERATE FOLDER AND MOVE ALL THE Learning-Mode-AI SERVICES INTO THAT FOLDER
# FOR IT TO WORK


version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

  main-backend:
    build:
      context: ./Learning-Mode-AI/backend
    container_name: main-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network

  youtube-info-service:
    build:
      context: ./Learning-Mode-AI-info-service
    env_file:
      - ./Learning-Mode-AI-info-service/.env
    container_name: info-service
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  ai-service:
    build:
      context: ./Learning-Mode-AI-ai-service
    container_name: ai-service
    ports:
      - "8082:8082"
    depends_on:
      - redis
    networks:
      - app-network

  video-processing-service:
    build:
      context: ./Learning-Mode-AI-snapshot-service
    container_name: snapshot-service
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - app-network

  quiz-service:
    build:
      context: ./Learning-Mode-AI-quiz-service
    container_name: quiz-service
    ports:
      - "8084:8084"
    depends_on:
      - redis
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
