name: Trigger Deployment

on:
  push:
    branches:
      - main

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deployment Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEPLOYMENT_PAT_R }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'learning-mode-ai',
              repo: 'learning-mode-ai-deployment',
              workflow_id: 'staging_deploy.yml',
              ref: 'staging',
            })